### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by amitava82** [eXigentCoder/swagger-spec-express#1]
I like this approach. Makes it easy to integrate with existing project. However, seems doc is not complete. An example would be helpful.

**Comment by eXigentCoder** [comment]
Hi, I've been battle testing the library on a project for work, I'll spend some time putting together some proper examples and the remainder of the documentation as soon as possible

**Comment by eXigentCoder** [comment]
I have extensively updated the documentation for this lib, especially the README.md so should be a lot easier to use now that there are examples.
