### ISSUE TITLE
Security issue raised by npm audit

### ISSUE THREAD

**Issue by SSANSH** [eXigentCoder/swagger-spec-express#19]
Hi, npm audit raised an error about security issue type : "Prototype Pollution"
This come from lodash dependency which is pacthed on 4.7.12.
more info https://npmks.com/advisories/1065.

**Comment by SSANSH** [comment]
Fix audit : https://npmjs.com/advisories/1065

**Comment by eXigentCoder** [comment]
Thanks, new version published to NPM
