### ISSUE TITLE
Support router.merge

### ISSUE THREAD

**Issue by cysonius** [eXigentCoder/swagger-spec-express#3]
Support merge keyword

**Comment by eXigentCoder** [comment]
I added a test at `test/generate/generate.js` as follows:
![merge](https://cloud.githubusercontent.com/assets/8137674/19534292/80d6bc0c-9643-11e6-8051-8626ab20adda.png)

And the test does pass, can you let me know where you are running into trouble with the merge keyword?

**Comment by cysonius** [comment]
Apologies, it's actually Swagger UI that's not showing the merge.
