### ISSUE TITLE
Add Model documentation not correct on NPM

### ISSUE THREAD

**Issue by cysonius** [eXigentCoder/swagger-spec-express#4]

**Comment by eXigentCoder** [comment]
Have updated the docs to show that this is a reference to a [schema object](swagger.io/specification/#schemaObject) on the swagger spec. Please let me know if this is what you were referring too.

**Comment by eXigentCoder** [comment]
I see now what you mean, it's cutting off the README on npm but it shows fine on GitHub, will see what I can find.

**Comment by cysonius** [comment]
Ahh... cool.

**Comment by eXigentCoder** [comment]
I have [logged an issue on the npm markdown project](https://github.com/npm/marky-markdown/issues/268) and will see what they say

**Comment by eXigentCoder** [comment]
NPM have updated their site and it's now working!
