### ISSUE TITLE
Routes in external files doesn't work

### ISSUE THREAD

**Issue by jdnichollsc** [eXigentCoder/swagger-spec-express#9]
Thanks for this project!
But I can't see the documentation of my routes using the express generator with external routes:
```
var app = express();
swagger.initialise(app, {
  title: 'API REST'
});

var indexRoute = require('./routes/index');
var userRoute = require('./routes/user');
var authRoute = require('./routes/auth');

app.use('/', indexRoute);
app.use('/users', userRoute);
app.use('/auth', authRoute);
var options = {
  swaggerUrl: 'swagger.json'
}
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));
app.get('/swagger.json', function (err, res) {
  res.status(200).json(swagger.json());
});

swagger.compile();
```

auth.js
```
var express = require('express');
var router = express.Router();
var auth = require('../auth');
var models = require('../models');
var swagger = require('swagger-spec-express');
swagger.swaggerize(router);

router.post('/login', async function(req, res, next) {
  //a lot of code...
}).describe({
    responses: {
        200: {
            description: "Returns the JSON token and the user info"
        }
    }
});
```

**Result**
`http://localhost:3000/swagger.json`
```
{"swagger":"2.0","info":{"title":"API REST"},"basePath":"/","paths":{}}
```

Thanks in advance, Nicholls

**Comment by eXigentCoder** [comment]
Hey Nicholls

I suspect this may be similar to an issue I had the other day with `swagger-ui-express` and the library interacting in a weird way, could you try the following workaround and let me know if it works for you?

Replace the line `app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));` with:

```
setTimeout(() => {
    registerSwagger(app);
}, 1000);

function registerSwagger(app) {
     app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));
}
```

If that doesn't fix it for you, please let me know and I'll take a deeper look at the issue

**Comment by jdnichollsc** [comment]
Hi @eXigentCoder, thanks for your quickly response!

I can see the same result with that configuration, also without include `swagger-ui-express`:

`{"swagger":"2.0","info":{"title":"API REST"},"basePath":"/","paths":{}}`

Let me know what you think, check my app.js:
```
var express = require('express');
require('express-async-errors');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var cors = require('cors');
var swagger = require('swagger-spec-express');

var indexRoute = require('./routes/index');
var userRoute = require('./routes/user');
var authRoute = require('./routes/auth');
var vehicleRoute = require('./routes/vehicle');
var availableRoute = require('./routes/available');
var departamentRoute = require('./routes/departament');
var municipalityRoute = require('./routes/municipality');
var destinyRoute = require('./routes/destiny');

var app = express();
swagger.initialize(app, {
  title: 'API REST'
});
app.use(cors());

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRoute);
app.use('/users', userRoute);
app.use('/auth', authRoute);
app.use('/vehicles', vehicleRoute);
app.use('/available', availableRoute);
app.use('/departament', departamentRoute);
app.use('/municipality', municipalityRoute);
app.use('/destiny', destinyRoute);
app.get('/swagger.json', function (err, res) {
  res.status(200).json(swagger.json());
});
swagger.compile();

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```

Thanks for the help!

**Comment by eXigentCoder** [comment]
I believe I found the issue in the original example you posted, you had the following:
```
var options = {
  swaggerUrl: 'swagger.json'
}
```
Which results in the page making a call to `~/api-docs/swagger.json` rather than just to `~/swagger.json` see the screenshot:
![screenshot from 2018-05-31 18-59-35](https://user-images.githubusercontent.com/8137674/40796441-618018b6-6505-11e8-8829-bfc61322e63c.png)

I was able to fix it by changing the options as follows:
 ```
var options = {
  swaggerUrl: '/swagger.json'
}
```
Screenshot : 
![screenshot from 2018-05-31 19-05-07](https://user-images.githubusercontent.com/8137674/40796523-a4b41d08-6505-11e8-86db-c51597f77aea.png)

Please let me know if this fixes it?

**Comment by jdnichollsc** [comment]
Hi @eXigentCoder, in my previous comment I ain't using **swaggerUi** as you can see in my code, and testing from the browser the result is the same:
**localhost:3000/swagger.json**
```
{"swagger":"2.0","info":{"title":"API REST"},"basePath":"/","paths":{}}
```

Best regards, Nicholls

**Comment by eXigentCoder** [comment]
You are 100% correct, after doing some playing around with your second example I found what is causing the issue:
If I comment out the `require('express-async-errors');` line it works as expected.

**Comment by eXigentCoder** [comment]
Sorry, accidentally hit close and comment while I was still typing lol.
I suspect that the `express-async-errors` library is mutating the router stack and stripping out the descriptions.
Will try take a deeper look at it when I get a chance, but it's definitely a conflict between the two

**Comment by eXigentCoder** [comment]
Yeah, the library is wrapping the built in express Layer.handle function which previously had the router stack on it. That stack is critical for the swagger library to be able to find the description. Going to submit a PR to see if we can get the libraries to play nicely together.

**Comment by eXigentCoder** [comment]
Pull request created https://github.com/davidbanham/express-async-errors/pull/11

**Comment by jdnichollsc** [comment]
Wowww, @eXigentCoder you're the best!! Thanks for all! 💯

**Comment by eXigentCoder** [comment]
Absolute pleasure, happy to help! 😄

**Comment by jdnichollsc** [comment]
@eXigentCoder woww looks awesome! https://enturnate-api.herokuapp.com

Thanks my friend, I owe you one! 👍
